<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Rovia.Core\Rovia.Core.csproj" />
    <ProjectReference Include="..\Rovia.Config\Rovia.Config.csproj" />
    <ProjectReference Include="..\Rovia.Backends\Rovia.Backends.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <AssemblyName>rovia</AssemblyName>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
